apiVersion: v1
kind: Service
metadata:
        name: ftps-service
        labels:
                app: ftps-jluknar
spec:
        selector:
                app: ftps-jluknar
        type: LoadBalancer
        ports:
                - port: 20
                  name: ftps-connect
                  targetPort: 20
                  nodePort: 20
                - port: 21
                  name: ftps-port
                  targetPort: 21
                  nodePort: 21
                - port: 30020
                  name: ftps-data
                  targetPort: 30020
                  nodePort: 30020

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: ftps-deployment
        labels:
                app: ftps-jluknar
spec:
        selector:
                matchLabels:
                        app: ftps-jluknar
        replicas: 1
        template:
                metadata:
                        name: ftps-pod
                        labels:
                                app: ftps-jluknar
                spec:
                        containers:
                                - name: ftps-container
                                  image: ftps
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 20
                                            name: ftps-connect
                                          - containerPort: 21
                                            name: ftps-port
                                          - containerPort: 30020
                                            name: ftps-data
