apiVersion: v1
kind: Service
metadata:
        name: grafana-service
        labels:
                app: grafana-jluknar
spec:
        selector:
                app: grafana-jluknar
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
                - port: 3000
                  name: grafana-port
                  targetPort: 3000
                  nodePort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: grafana-deployment
        labels:
                app: grafana-jluknar
spec:
        selector:
                matchLabels:
                        app: grafana-jluknar
        replicas: 1
        template:
                metadata:
                        name: grafana-pod
                        labels:
                                app: grafana-jluknar
                spec:
                        containers:
                                - name: grafana-container
                                  image: grafana
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 3000
                                            name: grafana-port
