apiVersion: v1
kind: Service
metadata:
        name: nginx-service
        labels:
                app: nginx-jluknar
spec:
        selector:
                app: nginx-jluknar
        type: LoadBalancer
        ports:
                - port: 80
                  name: nginx-http
                  targetPort: 80
                  nodePort: 80
                - port: 443
                  name: nginx-https
                  targetPort: 443
                  nodePort: 443
                - port: 30022
                  name: nginx-ssh
                  targetPort: 30022
                  nodePort: 30022

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx-deployment
        labels:
                app: nginx-jluknar
spec:
        selector:
                matchLabels:
                        app: nginx-jluknar
        replicas: 1
        template:
                metadata:
                        name: nginx-pod
                        labels:
                                app: nginx-jluknar
                spec:
                        containers:
                                - name: nginx-container
                                  image: nginx
                                  imagePullPolicy: Never
                                  ports:
                                          - containerPort: 80
                                            name: nginx-http
                                          - containerPort: 443
                                            name: nginx-https
                                          - containerPort: 22
                                            name: nginx-ssh
